[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Jan M <meiswinkel.jan@gmail.com>"]
description = ""
name = "autotrading"
version = "0.1.0"
[tool.poetry.dependencies]
ccxt = "^1.26"
python = "^3.7"
[tool.poetry.dev-dependencies]
